<Project>
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<!-- <Configurations>Debug;Release;</Configurations> -->
	</PropertyGroup>
	<PropertyGroup>
		<AiOrchestratorRepositoryDirectory>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))\</AiOrchestratorRepositoryDirectory>
	</PropertyGroup>
</Project>